import { Service, CreditPackage } from '@/types'

// ===================================
// CATÁLOGO COMPLETO DE SERVIÇOS
// ===================================

export const SERVICES_CATALOG: Omit<Service, 'createdAt' | 'updatedAt'>[] = [
  // 🏢 DOCUMENTOS INTERNACIONAIS
  {
    id: 'llc-usa-complete',
    slug: 'llc-usa-completa',
    name: 'LLC EUA Completa',
    description: 'Abertura completa de LLC nos Estados Unidos com toda documentação necessária',
    category: 'documents',
    price: 2997,
    priceType: 'one_time',
    credits: 2997,
    processingType: 'manual',
    estimatedTime: '24-48h',
    features: [
      'Registro oficial da LLC',
      'EIN (Número de Identificação Federal)',
      'Operating Agreement completo',
      'Documentação digital completa',
      'Suporte jurídico inicial',
      'Orientação sobre compliance',
    ],
    requirements: [
      'Passaporte válido',
      'Comprovante de endereço',
      'Propósito do negócio',
    ],
    formFields: [
      {
        id: 'company_name',
        name: 'company_name',
        label: 'Nome da Empresa',
        type: 'text',
        required: true,
        helperText: 'Nome desejado para sua LLC (verificaremos disponibilidade)',
      },
      {
        id: 'state',
        name: 'state',
        label: 'Estado para Registro',
        type: 'select',
        required: true,
        options: [
          { value: 'delaware', label: 'Delaware (Recomendado)' },
          { value: 'wyoming', label: 'Wyoming' },
          { value: 'florida', label: 'Florida' },
          { value: 'nevada', label: 'Nevada' },
        ],
      },
      {
        id: 'business_type',
        name: 'business_type',
        label: 'Tipo de Negócio',
        type: 'select',
        required: true,
        options: [
          { value: 'ecommerce', label: 'E-commerce' },
          { value: 'services', label: 'Serviços' },
          { value: 'consulting', label: 'Consultoria' },
          { value: 'technology', label: 'Tecnologia' },
          { value: 'other', label: 'Outro' },
        ],
      },
      {
        id: 'passport',
        name: 'passport',
        label: 'Passaporte',
        type: 'file',
        required: true,
        accept: 'image/*,application/pdf',
        maxSize: 5,
      },
      {
        id: 'address_proof',
        name: 'address_proof',
        label: 'Comprovante de Endereço',
        type: 'file',
        required: true,
        accept: 'image/*,application/pdf',
        maxSize: 5,
      },
    ],
    icon: 'Building2',
    popular: true,
    active: true,
  },

  // 🛍️ TIKTOK SHOPS
  {
    id: 'tiktok-shop-br',
    slug: 'tiktok-shop-brasil',
    name: 'TikTok Shop Brasil',
    description: 'Criação e configuração completa da sua loja no TikTok Shop Brasil',
    category: 'shops',
    price: 497,
    priceType: 'one_time',
    credits: 497,
    processingType: 'hybrid',
    estimatedTime: '4-8h',
    features: [
      'Criação da conta',
      'Verificação completa',
      'Configuração de pagamentos',
      'Setup inicial de produtos',
      'Integração com métodos de pagamento',
      'Treinamento básico',
    ],
    formFields: [
      {
        id: 'full_name',
        name: 'full_name',
        label: 'Nome Completo',
        type: 'text',
        required: true,
      },
      {
        id: 'cpf',
        name: 'cpf',
        label: 'CPF',
        type: 'text',
        required: true,
        validation: { pattern: '^[0-9]{11}$', message: 'CPF inválido' },
      },
      {
        id: 'birth_date',
        name: 'birth_date',
        label: 'Data de Nascimento',
        type: 'date',
        required: true,
      },
      {
        id: 'phone',
        name: 'phone',
        label: 'Telefone/WhatsApp',
        type: 'phone',
        required: true,
      },
      {
        id: 'store_name',
        name: 'store_name',
        label: 'Nome da Loja',
        type: 'text',
        required: true,
      },
      {
        id: 'store_category',
        name: 'store_category',
        label: 'Categoria Principal',
        type: 'select',
        required: true,
        options: [
          { value: 'fashion', label: 'Moda e Acessórios' },
          { value: 'beauty', label: 'Beleza e Cuidados' },
          { value: 'home', label: 'Casa e Decoração' },
          { value: 'electronics', label: 'Eletrônicos' },
          { value: 'sports', label: 'Esportes e Fitness' },
        ],
      },
      {
        id: 'documents',
        name: 'documents',
        label: 'Documentos (RG/CNH)',
        type: 'file',
        required: true,
        accept: 'image/*,application/pdf',
        maxSize: 5,
        multiple: true,
      },
    ],
    icon: 'ShoppingBag',
    popular: true,
    active: true,
  },

  {
    id: 'tiktok-shop-us',
    slug: 'tiktok-shop-usa',
    name: 'TikTok Shop USA',
    description: 'Criação e configuração completa da sua loja no TikTok Shop Estados Unidos',
    category: 'shops',
    price: 997,
    priceType: 'one_time',
    credits: 997,
    processingType: 'hybrid',
    estimatedTime: '4-8h',
    features: [
      'Criação da conta nos EUA',
      'Verificação completa',
      'Configuração de pagamentos internacionais',
      'Setup inicial de produtos',
      'Integração com Stripe/PayPal',
      'Orientação sobre impostos',
    ],
    formFields: [
      {
        id: 'full_name',
        name: 'full_name',
        label: 'Full Name',
        type: 'text',
        required: true,
      },
      {
        id: 'ssn_ein',
        name: 'ssn_ein',
        label: 'SSN or EIN',
        type: 'text',
        required: true,
        helperText: 'Social Security Number or Employer Identification Number',
      },
      {
        id: 'us_address',
        name: 'us_address',
        label: 'US Address',
        type: 'textarea',
        required: true,
        helperText: 'Physical address in the United States',
      },
      {
        id: 'phone',
        name: 'phone',
        label: 'US Phone Number',
        type: 'phone',
        required: true,
      },
      {
        id: 'store_name',
        name: 'store_name',
        label: 'Store Name',
        type: 'text',
        required: true,
      },
      {
        id: 'business_documents',
        name: 'business_documents',
        label: 'Business Documents',
        type: 'file',
        required: true,
        accept: 'image/*,application/pdf',
        maxSize: 10,
        multiple: true,
        helperText: 'LLC documents, EIN letter, etc.',
      },
    ],
    icon: 'ShoppingBag',
    active: true,
  },

  {
    id: 'tiktok-shop-uk',
    slug: 'tiktok-shop-uk',
    name: 'TikTok Shop UK',
    description: 'Criação e configuração completa da sua loja no TikTok Shop Reino Unido',
    category: 'shops',
    price: 997,
    priceType: 'one_time',
    credits: 997,
    processingType: 'hybrid',
    estimatedTime: '4-8h',
    features: [
      'Criação da conta no UK',
      'Verificação completa',
      'Configuração de pagamentos',
      'Setup inicial de produtos',
      'Compliance com regulamentos UK',
      'Suporte em inglês',
    ],
    formFields: [
      {
        id: 'full_name',
        name: 'full_name',
        label: 'Full Name',
        type: 'text',
        required: true,
      },
      {
        id: 'uk_company_number',
        name: 'uk_company_number',
        label: 'UK Company Number',
        type: 'text',
        required: true,
      },
      {
        id: 'uk_address',
        name: 'uk_address',
        label: 'UK Address',
        type: 'textarea',
        required: true,
      },
      {
        id: 'vat_number',
        name: 'vat_number',
        label: 'VAT Number (if applicable)',
        type: 'text',
        required: false,
      },
      {
        id: 'store_name',
        name: 'store_name',
        label: 'Store Name',
        type: 'text',
        required: true,
      },
      {
        id: 'business_documents',
        name: 'business_documents',
        label: 'Business Documents',
        type: 'file',
        required: true,
        accept: 'image/*,application/pdf',
        maxSize: 10,
        multiple: true,
      },
    ],
    icon: 'ShoppingBag',
    active: true,
  },

  // 🌐 PROXIES GLOBAIS
  {
    id: 'proxy-brasil',
    slug: 'proxy-brasil',
    name: 'Proxy Brasil',
    description: 'IP dedicado brasileiro com alta velocidade e disponibilidade',
    category: 'infrastructure',
    price: 37,
    priceType: 'monthly',
    credits: 37,
    processingType: 'automatic',
    estimatedTime: 'Imediato',
    features: [
      'IP dedicado brasileiro',
      'Velocidade 1Gbps',
      'Uptime 99.9%',
      'Dashboard de gerenciamento',
      'Suporte técnico',
      'Troca de IP sob demanda',
    ],
    formFields: [
      {
        id: 'usage_type',
        name: 'usage_type',
        label: 'Tipo de Uso',
        type: 'select',
        required: true,
        options: [
          { value: 'social_media', label: 'Redes Sociais' },
          { value: 'ecommerce', label: 'E-commerce' },
          { value: 'scraping', label: 'Web Scraping' },
          { value: 'general', label: 'Uso Geral' },
        ],
      },
      {
        id: 'quantity',
        name: 'quantity',
        label: 'Quantidade de IPs',
        type: 'number',
        required: true,
        validation: { min: 1, max: 100 },
      },
    ],
    icon: 'Globe',
    active: true,
  },

  {
    id: 'proxy-usa',
    slug: 'proxy-usa',
    name: 'Proxy USA',
    description: 'IP dedicado americano com alta performance',
    category: 'infrastructure',
    price: 65,
    priceType: 'monthly',
    credits: 65,
    processingType: 'automatic',
    estimatedTime: 'Imediato',
    features: [
      'IP dedicado dos EUA',
      'Múltiplas localizações (NY, LA, Chicago)',
      'Velocidade 1Gbps',
      'Uptime 99.9%',
      'Dashboard de gerenciamento',
      'Suporte 24/7',
    ],
    formFields: [
      {
        id: 'location',
        name: 'location',
        label: 'Localização Preferida',
        type: 'select',
        required: true,
        options: [
          { value: 'ny', label: 'New York' },
          { value: 'la', label: 'Los Angeles' },
          { value: 'chicago', label: 'Chicago' },
          { value: 'miami', label: 'Miami' },
        ],
      },
      {
        id: 'usage_type',
        name: 'usage_type',
        label: 'Tipo de Uso',
        type: 'select',
        required: true,
        options: [
          { value: 'social_media', label: 'Social Media' },
          { value: 'ecommerce', label: 'E-commerce' },
          { value: 'streaming', label: 'Streaming' },
          { value: 'general', label: 'General' },
        ],
      },
      {
        id: 'quantity',
        name: 'quantity',
        label: 'Quantity',
        type: 'number',
        required: true,
        validation: { min: 1, max: 100 },
      },
    ],
    icon: 'Globe',
    active: true,
  },

  {
    id: 'proxy-latam',
    slug: 'proxy-latam',
    name: 'Proxy LATAM',
    description: 'IPs dedicados da América Latina (México, Argentina, Chile)',
    category: 'infrastructure',
    price: 57,
    priceType: 'monthly',
    credits: 57,
    processingType: 'automatic',
    estimatedTime: 'Imediato',
    features: [
      'IPs de múltiplos países LATAM',
      'Alta velocidade',
      'Uptime garantido',
      'Dashboard centralizado',
      'Suporte em português/espanhol',
    ],
    formFields: [
      {
        id: 'country',
        name: 'country',
        label: 'País',
        type: 'select',
        required: true,
        options: [
          { value: 'mexico', label: 'México' },
          { value: 'argentina', label: 'Argentina' },
          { value: 'chile', label: 'Chile' },
          { value: 'colombia', label: 'Colômbia' },
        ],
      },
      {
        id: 'quantity',
        name: 'quantity',
        label: 'Quantidade',
        type: 'number',
        required: true,
        validation: { min: 1, max: 50 },
      },
    ],
    icon: 'Globe',
    active: true,
  },

  {
    id: 'proxy-europa',
    slug: 'proxy-europa',
    name: 'Proxy Europa',
    description: 'IPs dedicados europeus (UK, Alemanha, França)',
    category: 'infrastructure',
    price: 77,
    priceType: 'monthly',
    credits: 77,
    processingType: 'automatic',
    estimatedTime: 'Imediato',
    features: [
      'IPs de múltiplos países europeus',
      'Compliance GDPR',
      'Alta velocidade',
      'Uptime 99.9%',
      'Suporte multilíngue',
    ],
    formFields: [
      {
        id: 'country',
        name: 'country',
        label: 'País',
        type: 'select',
        required: true,
        options: [
          { value: 'uk', label: 'Reino Unido' },
          { value: 'germany', label: 'Alemanha' },
          { value: 'france', label: 'França' },
          { value: 'netherlands', label: 'Holanda' },
        ],
      },
      {
        id: 'quantity',
        name: 'quantity',
        label: 'Quantidade',
        type: 'number',
        required: true,
        validation: { min: 1, max: 50 },
      },
    ],
    icon: 'Globe',
    active: true,
  },

  // 👕 FABRICANTE WHITE-LABEL
  {
    id: 'fabricante-dropshipping',
    slug: 'fabricante-whitelabel',
    name: 'Acesso Fabricante White-Label',
    description: 'Acesso exclusivo ao nosso fabricante parceiro para dropshipping com marca própria',
    category: 'manufacturing',
    price: 97,
    priceType: 'one_time',
    credits: 97,
    processingType: 'hybrid',
    estimatedTime: '24h',
    features: [
      'Catálogo completo de produtos',
      'Aplicação de marca própria',
      'Preços de atacado',
      'Dropshipping automático',
      'Integração com sua loja',
      'Suporte dedicado',
    ],
    formFields: [
      {
        id: 'business_name',
        name: 'business_name',
        label: 'Nome do Negócio',
        type: 'text',
        required: true,
      },
      {
        id: 'product_categories',
        name: 'product_categories',
        label: 'Categorias de Interesse',
        type: 'multiselect',
        required: true,
        options: [
          { value: 'clothing', label: 'Roupas' },
          { value: 'accessories', label: 'Acessórios' },
          { value: 'home', label: 'Casa e Decoração' },
          { value: 'fitness', label: 'Fitness e Esportes' },
        ],
      },
      {
        id: 'monthly_volume',
        name: 'monthly_volume',
        label: 'Volume Mensal Estimado',
        type: 'select',
        required: true,
        options: [
          { value: '0-50', label: '0-50 peças' },
          { value: '51-200', label: '51-200 peças' },
          { value: '201-500', label: '201-500 peças' },
          { value: '500+', label: '500+ peças' },
        ],
      },
      {
        id: 'branding',
        name: 'branding',
        label: 'Deseja aplicar sua marca?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Sim' },
          { value: 'no', label: 'Não' },
        ],
      },
      {
        id: 'logo',
        name: 'logo',
        label: 'Logo da Marca (se aplicável)',
        type: 'file',
        required: false,
        accept: 'image/*',
        maxSize: 5,
        conditional: {
          field: 'branding',
          value: 'yes',
        },
      },
    ],
    icon: 'Package',
    active: true,
  },

  // 🤖 MARKETING AUTOMATIZADO
  {
    id: 'ia-anuncios',
    slug: 'ia-anuncios-automatizados',
    name: 'IA Anúncios (Pacote Completo)',
    description: 'Sistema completo de criação e otimização automática de campanhas de anúncios com IA',
    category: 'marketing',
    price: 147,
    priceType: 'monthly',
    credits: 147,
    processingType: 'automatic',
    estimatedTime: '2h',
    features: [
      'Criação automática de campanhas',
      'Otimização em tempo real',
      'A/B testing automático',
      'Relatórios detalhados',
      'Integração com Facebook, Google, TikTok',
      'Suporte especializado',
    ],
    formFields: [
      {
        id: 'platforms',
        name: 'platforms',
        label: 'Plataformas de Anúncio',
        type: 'multiselect',
        required: true,
        options: [
          { value: 'facebook', label: 'Facebook/Instagram' },
          { value: 'google', label: 'Google Ads' },
          { value: 'tiktok', label: 'TikTok Ads' },
        ],
      },
      {
        id: 'monthly_budget',
        name: 'monthly_budget',
        label: 'Orçamento Mensal de Anúncios',
        type: 'select',
        required: true,
        options: [
          { value: '500-1000', label: 'R$ 500 - R$ 1.000' },
          { value: '1000-3000', label: 'R$ 1.000 - R$ 3.000' },
          { value: '3000-5000', label: 'R$ 3.000 - R$ 5.000' },
          { value: '5000+', label: 'R$ 5.000+' },
        ],
      },
      {
        id: 'business_niche',
        name: 'business_niche',
        label: 'Nicho do Negócio',
        type: 'text',
        required: true,
        helperText: 'Ex: Moda feminina, Suplementos, Cursos online',
      },
      {
        id: 'target_audience',
        name: 'target_audience',
        label: 'Público-Alvo',
        type: 'textarea',
        required: true,
        helperText: 'Descreva seu público-alvo (idade, localização, interesses)',
      },
      {
        id: 'website_url',
        name: 'website_url',
        label: 'URL do Website/Loja',
        type: 'text',
        required: true,
      },
    ],
    icon: 'Sparkles',
    popular: true,
    active: true,
  },

  // 📱 APP PERSONALIZADO
  {
    id: 'app-personalizado',
    slug: 'app-personalizado',
    name: 'App Personalizado',
    description: 'Aplicativo mobile personalizado para iOS e Android com sua marca',
    category: 'technology',
    price: 4997,
    priceType: 'one_time',
    credits: 4997,
    processingType: 'manual',
    estimatedTime: '5-7 dias',
    features: [
      'iOS e Android nativos',
      'Design personalizado',
      'Painel administrativo web',
      'Notificações push',
      'Integração com APIs',
      'Publicação nas stores',
      '3 meses de suporte incluso',
    ],
    formFields: [
      {
        id: 'app_name',
        name: 'app_name',
        label: 'Nome do App',
        type: 'text',
        required: true,
      },
      {
        id: 'app_type',
        name: 'app_type',
        label: 'Tipo de App',
        type: 'select',
        required: true,
        options: [
          { value: 'ecommerce', label: 'E-commerce' },
          { value: 'service', label: 'Serviços' },
          { value: 'content', label: 'Conteúdo/Blog' },
          { value: 'community', label: 'Comunidade/Social' },
          { value: 'other', label: 'Outro' },
        ],
      },
      {
        id: 'features_needed',
        name: 'features_needed',
        label: 'Funcionalidades Necessárias',
        type: 'multiselect',
        required: true,
        options: [
          { value: 'login', label: 'Login/Cadastro' },
          { value: 'payment', label: 'Pagamentos' },
          { value: 'chat', label: 'Chat' },
          { value: 'notifications', label: 'Notificações' },
          { value: 'geolocation', label: 'Geolocalização' },
          { value: 'camera', label: 'Câmera' },
        ],
      },
      {
        id: 'description',
        name: 'description',
        label: 'Descrição do Projeto',
        type: 'textarea',
        required: true,
        helperText: 'Descreva detalhadamente o que você precisa',
      },
      {
        id: 'reference_apps',
        name: 'reference_apps',
        label: 'Apps de Referência',
        type: 'textarea',
        required: false,
        helperText: 'Liste apps que você gosta e quer usar como inspiração',
      },
      {
        id: 'brand_assets',
        name: 'brand_assets',
        label: 'Assets da Marca (logo, cores, etc.)',
        type: 'file',
        required: false,
        accept: 'image/*,.zip',
        maxSize: 20,
        multiple: true,
      },
    ],
    icon: 'Smartphone',
    active: true,
  },

  // 🔐 BUSINESS MANAGERS
  {
    id: 'bm-facebook',
    slug: 'business-manager-facebook',
    name: 'Business Manager Facebook',
    description: 'Business Manager Facebook pré-verificado e pronto para usar',
    category: 'business_managers',
    price: 350,
    priceType: 'one_time',
    credits: 350,
    processingType: 'hybrid',
    estimatedTime: '6-12h',
    features: [
      'Conta pré-verificada',
      'Configuração de segurança',
      'Método de pagamento configurado',
      'Limites liberados',
      'Treinamento de uso',
      '30 dias de suporte',
    ],
    formFields: [
      {
        id: 'facebook_personal_url',
        name: 'facebook_personal_url',
        label: 'URL do Perfil Pessoal Facebook',
        type: 'text',
        required: true,
      },
      {
        id: 'business_name',
        name: 'business_name',
        label: 'Nome do Negócio',
        type: 'text',
        required: true,
      },
      {
        id: 'niche',
        name: 'niche',
        label: 'Nicho/Segmento',
        type: 'text',
        required: true,
      },
      {
        id: 'monthly_budget',
        name: 'monthly_budget',
        label: 'Orçamento Mensal Estimado',
        type: 'select',
        required: true,
        options: [
          { value: '500-1000', label: 'R$ 500 - R$ 1.000' },
          { value: '1000-5000', label: 'R$ 1.000 - R$ 5.000' },
          { value: '5000+', label: 'R$ 5.000+' },
        ],
      },
    ],
    icon: 'Facebook',
    active: true,
  },

  {
    id: 'bm-tiktok',
    slug: 'business-manager-tiktok',
    name: 'Business Manager TikTok',
    description: 'TikTok Ads Manager pré-configurado e verificado',
    category: 'business_managers',
    price: 300,
    priceType: 'one_time',
    credits: 300,
    processingType: 'hybrid',
    estimatedTime: '6-12h',
    features: [
      'Conta verificada',
      'Configuração completa',
      'Pixel instalado',
      'Métodos de pagamento',
      'Guia de uso',
      '30 dias de suporte',
    ],
    formFields: [
      {
        id: 'tiktok_username',
        name: 'tiktok_username',
        label: 'Username TikTok',
        type: 'text',
        required: true,
      },
      {
        id: 'business_name',
        name: 'business_name',
        label: 'Nome do Negócio',
        type: 'text',
        required: true,
      },
      {
        id: 'website_url',
        name: 'website_url',
        label: 'URL do Website',
        type: 'text',
        required: true,
      },
    ],
    icon: 'TrendingUp',
    active: true,
  },

  {
    id: 'bm-google',
    slug: 'business-manager-google',
    name: 'Business Manager Google',
    description: 'Conta Google Ads pré-verificada com configurações otimizadas',
    category: 'business_managers',
    price: 450,
    priceType: 'one_time',
    credits: 450,
    processingType: 'hybrid',
    estimatedTime: '6-12h',
    features: [
      'Conta Google Ads verificada',
      'Google Analytics integrado',
      'Conversões configuradas',
      'Métodos de pagamento',
      'Consulta de otimização',
      '30 dias de suporte',
    ],
    formFields: [
      {
        id: 'google_email',
        name: 'google_email',
        label: 'Email Google',
        type: 'email',
        required: true,
      },
      {
        id: 'business_name',
        name: 'business_name',
        label: 'Nome do Negócio',
        type: 'text',
        required: true,
      },
      {
        id: 'website_url',
        name: 'website_url',
        label: 'URL do Website',
        type: 'text',
        required: true,
      },
      {
        id: 'campaign_type',
        name: 'campaign_type',
        label: 'Tipo de Campanha Principal',
        type: 'select',
        required: true,
        options: [
          { value: 'search', label: 'Pesquisa' },
          { value: 'display', label: 'Display' },
          { value: 'shopping', label: 'Shopping' },
          { value: 'video', label: 'Vídeo (YouTube)' },
        ],
      },
    ],
    icon: 'Chrome',
    active: true,
  },

  // 🌐 E-COMMERCE PRONTO
  {
    id: 'site-ecommerce',
    slug: 'site-ecommerce-pronto',
    name: 'Site E-commerce HTML Pronto',
    description: 'Site de e-commerce completo, responsivo e pronto para usar',
    category: 'ecommerce',
    price: 1997,
    priceType: 'one_time',
    credits: 1997,
    processingType: 'automatic',
    estimatedTime: '24h',
    features: [
      'Design mobile-first responsivo',
      '20 produtos pré-integrados',
      'APIs de pagamento (Mercado Pago, Asaas)',
      'Painel administrativo',
      'SEO otimizado',
      'Hospedagem inclusa (3 meses)',
      'SSL certificado',
    ],
    formFields: [
      {
        id: 'store_name',
        name: 'store_name',
        label: 'Nome da Loja',
        type: 'text',
        required: true,
      },
      {
        id: 'domain',
        name: 'domain',
        label: 'Domínio Desejado',
        type: 'text',
        required: true,
        helperText: 'Ex: minhalojanome.com (verificaremos disponibilidade)',
      },
      {
        id: 'niche',
        name: 'niche',
        label: 'Nicho/Segmento',
        type: 'select',
        required: true,
        options: [
          { value: 'fashion', label: 'Moda' },
          { value: 'beauty', label: 'Beleza' },
          { value: 'tech', label: 'Tecnologia' },
          { value: 'home', label: 'Casa e Decoração' },
          { value: 'sports', label: 'Esportes' },
          { value: 'other', label: 'Outro' },
        ],
      },
      {
        id: 'color_scheme',
        name: 'color_scheme',
        label: 'Esquema de Cores',
        type: 'select',
        required: true,
        options: [
          { value: 'modern', label: 'Moderno (preto e branco)' },
          { value: 'vibrant', label: 'Vibrante (cores fortes)' },
          { value: 'elegant', label: 'Elegante (tons suaves)' },
          { value: 'custom', label: 'Personalizado' },
        ],
      },
      {
        id: 'logo',
        name: 'logo',
        label: 'Logo da Loja',
        type: 'file',
        required: false,
        accept: 'image/*',
        maxSize: 5,
      },
      {
        id: 'products_info',
        name: 'products_info',
        label: 'Informações dos Produtos',
        type: 'textarea',
        required: true,
        helperText: 'Liste os produtos que deseja vender',
      },
    ],
    icon: 'Store',
    popular: true,
    active: true,
  },

  // ⚖️ CONSULTORIA JURÍDICA
  {
    id: 'consultoria-juridica',
    slug: 'consultoria-juridica',
    name: 'Consultoria Jurídica',
    description: 'Consultoria jurídica especializada em negócios internacionais',
    category: 'consulting',
    price: 180,
    priceType: 'one_time',
    credits: 180,
    processingType: 'manual',
    estimatedTime: 'Agendamento',
    features: [
      'Consulta de 1 hora',
      'Análise de documentos',
      'Orientação sobre compliance',
      'Estruturação de negócios',
      'Impostos internacionais',
      'Gravação da reunião',
    ],
    formFields: [
      {
        id: 'consultation_topic',
        name: 'consultation_topic',
        label: 'Tópico da Consultoria',
        type: 'select',
        required: true,
        options: [
          { value: 'llc', label: 'LLC e Estruturação nos EUA' },
          { value: 'international_business', label: 'Negócios Internacionais' },
          { value: 'taxes', label: 'Impostos e Compliance' },
          { value: 'contracts', label: 'Contratos e Acordos' },
          { value: 'other', label: 'Outro Assunto' },
        ],
      },
      {
        id: 'description',
        name: 'description',
        label: 'Descrição do Caso',
        type: 'textarea',
        required: true,
        helperText: 'Descreva sua situação e o que precisa de orientação',
      },
      {
        id: 'preferred_date',
        name: 'preferred_date',
        label: 'Data Preferida',
        type: 'date',
        required: true,
      },
      {
        id: 'preferred_time',
        name: 'preferred_time',
        label: 'Horário Preferido',
        type: 'select',
        required: true,
        options: [
          { value: 'morning', label: 'Manhã (9h-12h)' },
          { value: 'afternoon', label: 'Tarde (14h-17h)' },
          { value: 'evening', label: 'Noite (18h-20h)' },
        ],
      },
      {
        id: 'documents',
        name: 'documents',
        label: 'Documentos Relacionados',
        type: 'file',
        required: false,
        accept: 'image/*,application/pdf',
        maxSize: 10,
        multiple: true,
      },
    ],
    icon: 'Scale',
    active: true,
  },
]

// ===================================
// PACOTES DE CRÉDITOS
// ===================================

export const CREDIT_PACKAGES: Omit<CreditPackage, 'createdAt'>[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 497,
    credits: 600,
    discount: 20,
    effectivePrice: 0.83,
    bestFor: '1-2 serviços',
    popular: false,
    active: true,
  },
  {
    id: 'business',
    name: 'Business',
    price: 997,
    credits: 1400,
    discount: 40,
    effectivePrice: 0.71,
    bestFor: '3-5 serviços',
    popular: true,
    active: true,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 2997,
    credits: 5000,
    discount: 67,
    effectivePrice: 0.60,
    bestFor: '6-10 serviços',
    popular: false,
    active: true,
  },
  {
    id: 'empire',
    name: 'Empire',
    price: 4997,
    credits: 10000,
    discount: 100,
    effectivePrice: 0.50,
    bestFor: 'Clientes corporativos',
    popular: false,
    active: true,
  },
]

// ===================================
// CATEGORIAS
// ===================================

export const SERVICE_CATEGORIES = {
  documents: {
    name: 'Documentos Internacionais',
    icon: 'FileText',
    description: 'LLCs, registros e documentação oficial',
  },
  shops: {
    name: 'TikTok Shops',
    icon: 'ShoppingBag',
    description: 'Lojas TikTok Shop em múltiplos países',
  },
  infrastructure: {
    name: 'Infraestrutura Global',
    icon: 'Server',
    description: 'Proxies e infraestrutura técnica',
  },
  manufacturing: {
    name: 'Fabricação',
    icon: 'Package',
    description: 'White-label e dropshipping',
  },
  marketing: {
    name: 'Marketing',
    icon: 'Megaphone',
    description: 'Automação e campanhas de marketing',
  },
  technology: {
    name: 'Tecnologia',
    icon: 'Code',
    description: 'Apps e desenvolvimento customizado',
  },
  business_managers: {
    name: 'Business Managers',
    icon: 'Settings',
    description: 'Contas de anúncios verificadas',
  },
  ecommerce: {
    name: 'E-commerce',
    icon: 'Store',
    description: 'Sites e lojas virtuais',
  },
  consulting: {
    name: 'Consultoria',
    icon: 'Users',
    description: 'Consultorias especializadas',
  },
  support: {
    name: 'Suporte',
    icon: 'MessageCircle',
    description: 'Suporte e atendimento',
  },
} as const
